### ISSUE TITLE
[Bug] The type from amount is a string not a number

### ISSUE THREAD

**Issue by ThallesP** [rocketseat-education/ignite-template-tests-challenge#1]
Hello!

I was doing this challenge and I found a bug.

The type of `amount` from the table `statements` is `decimal` and because of that TypeORM returns it as a `string` to have a SafeGuard and this happens because JavaScript can't represent all the numbers, you can read more about this here: https://github.com/typeorm/typeorm/issues/873#issuecomment-328912050.

Because of that the balance will be concatenated and causing not expected balances.

![Balance property is null](https://user-images.githubusercontent.com/76017384/141710339-1acf2856-5943-47e8-be18-dc2c3badeca3.png)

![Balance property as a string](https://user-images.githubusercontent.com/76017384/141710906-199bf170-26eb-4ce9-a0e1-700bb2c0fbd0.png)

I solved this by using a transformer that converts the string to float:
```ts
export class ColumnNumericTransformer {
  to(data: number): number {
    return data;
  }
  from(data: string): number {
    return parseFloat(data);
  }
}
```

entities/Statement.ts
```ts
@Column("decimal", {
    precision: 5,
    scale: 2,
    transformer: new ColumnNumericTransformer(),
  })
  amount: number;
 ```
 
 And also, `dotenv` is not being imported in `app.ts`.

**Comment by 8bitbeard** [comment]
Thanks for the solution @ThallesP ! One of my integration tests was "failing" because of this bug, and after implementing your solution, the app worked as expected!

Maybe you can open a pull request to this repo with your solution, to prevent this to happen to future students!

**Comment by ThallesP** [comment]
> Thanks for the solution @ThallesP ! One of my integration tests was "failing" because of this bug, and after implementing your solution, the app worked as expected!
> 
> Maybe you can open a pull request to this repo with your solution, to prevent this to happen to future students!

Hello, good to know that worked for you! I did a pull request now: #2 that fixes the two issues.
